### ISSUE TITLE
Rename "phoenix" references to "kitura"

### ISSUE THREAD

**Issue by kfbishop** [IBM-Swift/Kitura-CouchDB#1]
Several places in source and samples makes references to "pheonix".  These should be renamed to "kitura".

**Comment by chrisozenne** [comment]
I have a pending PR (https://github.com/IBM-Swift/Kitura-CouchDB/pull/5) which changes `phoenix` to `kitura_test_db`

**Comment by dfirsht** [comment]
Fixed in PR #5
