### ISSUE TITLE
How to get out of the Callback Hell

### ISSUE THREAD

**Issue by hendriku** [IBM-Swift/Kitura-CouchDB#106]
I am wondering if there is a way to use this repository and avoid the Callback Hell? 

Promises or Swift5 `Result` would be good candidates to do so IMO. Are there any implementation plans?

**Comment by ianpartridge** [comment]
I think the long-term "plan" is for `async/await` to save us... In the short/medium term we have no plans to make large changes to the public API so I'm afraid I'm going to close this for now.
