### ISSUE TITLE
Move to travis-ci.com (instead of travis.org)

### ISSUE THREAD

**Issue by nathanfallet** [IBM-Swift/Kitura-CouchDB#118]
The old travis.org service is [no longer available](https://blog.travis-ci.com/2021-05-07-orgshutdown).
You need to activate something in order to move the CI to travis-ci.com. PRs won't be able to get merged otherwise

**Comment by dannys42** [comment]
Sorry for the slow progress, I'm attempting to migrate this to travis-ci.com ([PR](https://github.com/Kitura/Kitura-CouchDB/pull/119)), but  it looks like the unit tests rely on access to a CouchDB server I do not have access to.
