### ISSUE TITLE
Batch delete/update commands

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura-CouchDB#14]
The problem I am facing is that I have a list of (ID, Revision) pairs, and I would like to delete all of these documents or update them in batch. This can be pulled off by iterating through each of these (ID, rev) pairs and calling the delete command each time. The problem with this approach is that each of those deletes are asynchronous, therefore it is immensely difficult to determine when all of them have completed. A promise framework or something similar could be useful here.

**Comment by corcoja** [comment]
Feature added in release 1.7.1. See here: https://github.com/IBM-Swift/Kitura-CouchDB/releases/tag/1.7.1

**Comment by Andrew-Lees11** [comment]
Closing since feature was added to CouchDB
