### ISSUE TITLE
Problems with using boolean on Cloudant, no problem on CouchDB

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura-CouchDB#20]
Perhaps this identifies some strange differences between Cloudant and CouchDB, but we were using a field that is a boolean. All of our tests pass when using CouchDB, but they failed when using Cloudant. We changed the value from using a native boolean type to an integer (0 or 1 for false and true respectively) and the issue was resolved.

**Comment by shmuelk** [comment]
@rfdickerson As of now Kitura-CouchDB treats the JSON payload sent to the database as GIGO. It isn't touched at all. Do you expect it to be scanned and modified?
