### ISSUE TITLE
Can't use "_all_docs?include_docs=true" in retrieve argument

### ISSUE THREAD

**Issue by JohnBehnke** [IBM-Swift/Kitura-CouchDB#21]
I'm trying to retrieve all documents in the database. While I can easily use "_all_docs" as the id argument, it only returns the documents without the docs' values, which in my case I need. I know the "?" gets escaped out as part of Kitura Net, but I'm wondering if there is a way around this perhaps. The error I get is: Error: not_found, reason: missing Code: 404. I know if I don't escape the ?, it works.

**Comment by shmuelk** [comment]
@JohnBehnke Please try out the new API that was just added to solve your problem.

**Comment by ianpartridge** [comment]
Closing this as fixed, please reopen if any problem are found.
