### ISSUE TITLE
port in ConnectionProperties should be an Int

### ISSUE THREAD

**Issue by akrabat** [IBM-Swift/Kitura-CouchDB#25]
The `port` parameter for `ConnectionProperties` is an `Int16` which seems a bit specific. I'm currently having to convert a variable of type `Int` to `Int16` which seems like "busy work"...

``` swift
let connectionProperties = ConnectionProperties(
    host: host,
    port: Int16(port),
    secured: secured
)
```

Can we make it an `Int` ?

**Comment by Andrew-Lees11** [comment]
We will implement this change with the next breaking version of Kitura-CouchDB

**Comment by Andrew-Lees11** [comment]
port is limited to UInt16 and numbers larger than that will cause a fatal error. You can avoid the cast to a UInt16 either by entering the port in the connection properties initializer:
```swift
let connectionProperties = ConnectionProperties(
    host: host,
    port: 5432,
    secured: secured
)
```
Or by defining the type when you set the value:
```swift
let port: UInt16 = 5432
```
