### ISSUE TITLE
queryByView ignores params with cloudant db

### ISSUE THREAD

**Issue by Spriter** [IBM-Swift/Kitura-CouchDB#54]
Hey guys,

I have a problem with the queryByView method. 

```
queryByView(_ view: String, ofDesign design: String, usingParameters params: [Database.QueryParameters], callback: @escaping (JSON?, NSError?) -> ())
```

It seems to ignore any key parameters using cloudant db. For example using key "user@mail.com" results in getting all documents and not only the doc with key "user@mail.com". It is working the right way using CouchDB 2.0.

Any Idea ?

Best regards
Marcel

**Comment by Spriter** [comment]
Ok Linux and NSString seems to be the problem. This is the fix.
```        
#if os(Linux)
let keyParam = mail
#else
 let keyParam = NSString(string: mail)
#endif
```

**Comment by Andrew-Lees11** [comment]
Closing since, as of Swift 4, you should not need to use NSString and this should no longer be an issue.
