### ISSUE TITLE
Support for Codable JSON rather than SwiftyJSON?

### ISSUE THREAD

**Issue by jthomas** [IBM-Swift/Kitura-CouchDB#73]
Are there any plans to move from using SwiftyJSON to supporting the Codable protocol for JSON within this proejct?

**Comment by ianpartridge** [comment]
Yes, this is a good idea that we'd like to pursue. Currently we don't have anyone assigned to it, so if someone from the community would like to work on this we'd love them to!

**Comment by Andrew-Lees11** [comment]
This has been implemented in this [pr](https://github.com/IBM-Swift/Kitura-CouchDB/pull/86) which has now been merged and tagged in CouchDB 3.0.0. This change replaces the SwiftyJSON API with the new `Document` protocol which used Codable.
